const SUPABASE_URL='https://yhdhoqtibqqrocsbvoth.supabase.co';
const SUPABASE_KEY='sb_publishable_7rqGyn_z2UqkS6Vzk0s7YA_52Ldru-i';
const sb=window.supabase?.createClient(SUPABASE_URL,SUPABASE_KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true,flowType:'pkce'}});
const K='framehouse-final',PK=K+'-people',stages=['Development','Pre-production','Production','Post-production','Complete'];
const raw={
'Feature Film':[['Development','Lock screenplay'],['Development','Creative treatment + budget'],['Pre-production','Attach key crew'],['Pre-production','Casting, locations + permits'],['Pre-production','Schedule, storyboard + call sheets'],['Production','Principal photography'],['Production','Daily media backups'],['Post-production','Assembly edit'],['Post-production','Picture lock, sound + grade'],['Complete','Masters, QC + delivery']],
'Short Film':[['Development','Lock screenplay + budget'],['Pre-production','Crew, casting + location'],['Pre-production','Shot list + schedule'],['Production','Principal photography'],['Post-production','Assembly + picture lock'],['Post-production','Sound, grade + titles'],['Complete','Final exports + festival package']],
'Documentary':[['Development','Research, access + treatment'],['Development','Budget + rights plan'],['Pre-production','Contributor outreach'],['Pre-production','Interview / field schedule'],['Production','Interviews + observational filming'],['Production','Logging + backups'],['Post-production','Transcripts + assembly'],['Post-production','Picture lock, archive clearance + grade'],['Complete','Masters, captions + delivery']],
'Series':[['Development','Series bible + episode scripts'],['Development','Season budget'],['Pre-production','Department heads, casting + locations'],['Pre-production','Master production schedule'],['Production','Episode production'],['Post-production','Editorial workflow + episode locks'],['Post-production','Sound, grade + masters'],['Complete','Season delivery package']],
'Music Video':[['Development','Concept, treatment + budget'],['Pre-production','Artist styling / casting'],['Pre-production','Locations, art + storyboard'],['Pre-production','Crew, equipment + schedule'],['Production','Principal photography'],['Post-production','Offline edit + VFX'],['Post-production','Grade + online'],['Complete','Masters + cutdowns']],
'Commercial':[['Development','Brief, treatment + estimate'],['Pre-production','Client treatment approval'],['Pre-production','Casting / set / location'],['Pre-production','Storyboard + PPM'],['Production','Principal photography'],['Post-production','Offline + client review'],['Post-production','VFX, grade, mix + online'],['Complete','Masters + aspect ratios']],
'Branded Film':[['Development','Brand brief + story treatment'],['Development','Budget + approvals'],['Pre-production','Contributors, locations + schedule'],['Production','Interviews + B-roll'],['Post-production','Story edit + brand review'],['Post-production','Grade, mix + graphics'],['Complete','Master + social cutdowns']],
'Corporate Film':[['Development','Objectives, messages + scope'],['Pre-production','Interviewee list + questions'],['Pre-production','Location + schedule'],['Production','Interviews + facility B-roll'],['Post-production','Assembly + stakeholder review'],['Post-production','Graphics, subtitles, grade + mix'],['Complete','Master + presentation versions']],
'Photoshoot':[['Development','Creative brief, references + usage'],['Pre-production','Moodboard + shot list'],['Pre-production','Crew / photographer booking'],['Pre-production','Talent, styling + HMU'],['Pre-production','Studio / location + lighting plan'],['Production','Shoot day'],['Production','On-set selects + backups'],['Post-production','Contact sheet + selects'],['Post-production','Retouching + colour'],['Complete','High-res + web delivery']],
'Fashion Editorial':[['Development','Editorial concept + usage brief'],['Pre-production','Moodboard + story sequence'],['Pre-production','Model, styling + HMU'],['Pre-production','Location + call sheet'],['Production','Editorial shoot'],['Post-production','Image selects + retouching'],['Post-production','Layout / publication review'],['Complete','Final delivery']],
'Product Shoot':[['Development','Product brief, specs + budget'],['Pre-production','Reference board + shot list'],['Pre-production','Product / prop inventory'],['Pre-production','Studio + lighting tests'],['Production','Hero + detail photography'],['Production','Asset backup + naming'],['Post-production','Selects, cleanup + retouching'],['Post-production','Colour consistency QC'],['Complete','All required exports']],
'Event Coverage':[['Development','Coverage brief + deliverables'],['Pre-production','Run of show + venue access'],['Pre-production','Crew, equipment + VIP moments'],['Production','Event coverage + interviews'],['Production','Media backups'],['Post-production','Selects + highlight edit'],['Post-production','Client review + retouching'],['Complete','Final gallery / film']],
'Social Content Campaign':[['Development','Objectives, platforms + content pillars'],['Development','Deliverables matrix'],['Pre-production','Scripts / hooks / shot lists'],['Pre-production','Talent, locations + props'],['Production','Batch content shoot'],['Post-production','Vertical edits + captions'],['Post-production','Approval + revisions'],['Complete','Platform-ready exports']],
'Podcast / Interview':[['Development','Guest brief + research'],['Pre-production','Guest confirmation + questions'],['Pre-production','Studio, camera, sound + lighting'],['Production','Record interview'],['Production','Backup audio + video'],['Post-production','Sync, edit + audio cleanup'],['Post-production','Graphics, captions + clips'],['Complete','Episode + social exports']],
'Other':[['Development','Define brief, scope + budget'],['Pre-production','Production plan + logistics'],['Production','Execute production + backups'],['Post-production','First edit / selects'],['Post-production','Review + revisions'],['Complete','Final QC + delivery']]
};
const $=id=>document.getElementById(id),uid=()=>crypto.randomUUID?.()||String(Date.now()+Math.random()),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const parse=k=>{try{let x=JSON.parse(localStorage.getItem(k)||'[]');return Array.isArray(x)?x:[]}catch{return[]}},legacy={Feature:'Feature Film',Short:'Short Film'};
const guess=n=>/edit|lock|grade|sound|retouch|export|deliver|review/i.test(n)?'Post-production':/shoot|photograph|record|coverage|filming|interview/i.test(n)?'Production':/brief|script|research|treatment|concept|budget|scope/i.test(n)?'Development':'Pre-production';
const normT=t=>({id:t.id||uid(),name:t.name||'Untitled task',stage:stages.includes(t.stage)?t.stage:guess(t.name),date:t.date||'',done:!!t.done,urgency:['low','medium','high'].includes(t.urgency)?t.urgency:'medium',person:t.person||'',completedBy:t.completedBy||'',completedAt:t.completedAt||''});
const normP=p=>{let type=legacy[p.type]||p.type||'Other';if(!raw[type])type='Other';return{id:p.id||uid(),name:p.name||'Untitled project',type,status:stages.includes(p.status)?p.status:'Development',date:p.date||'',desc:p.desc||'',tasks:(p.tasks||[]).map(normT)}};
let projects=parse(K).map(normP),people=parse(PK).map(p=>({...p,id:p.id||uid(),department:p.department||''})),selected=null,tab='tasks',user=null,profile=null,profileFirstTime=false;
const persist=()=>{localStorage.setItem(K,JSON.stringify(projects));localStorage.setItem(PK,JSON.stringify(people))},save=()=>{persist();render()};persist();
const empty=(a,b)=>`<div class="empty"><b>${a}</b>${b}</div>`,pct=p=>p.tasks.length?Math.round(p.tasks.filter(t=>t.done).length/p.tasks.length*100):0;
function card(p){return `<article class="card"><div><span class="pill">${esc(p.type)}</span> <span class="pill">${esc(p.status)}</span></div><h3>${esc(p.name)}</h3><p class="muted">${esc(p.desc||'No notes yet.')}</p><div class="bar"><i style="width:${pct(p)}%"></i></div><div class="cardfoot"><span>${pct(p)}% · ${esc(p.status)}</span><span>${p.date||'No target'}</span></div><div class="actions" style="margin-top:14px"><button class="btn ghost" data-open="${p.id}">Open project →</button><button class="btn ghost" data-newtask="${p.id}">+ Task</button></div></article>`}
function taskRow(t,p){let pe=people.find(x=>x.id===t.person);return `<div class="row"><input class="check" type="checkbox" data-toggle="${p.id}|${t.id}" ${t.done?'checked':''}><div class="rowmain"><b>${esc(t.name)}</b><small>${esc(p.name)} · ${pe?esc(pe.name):'Unassigned'}${t.done&&t.completedBy?' · Completed by '+esc(t.completedBy):''}</small></div><span class="stagepill">${esc(t.stage)}</span><span class="urgency ${t.urgency}">${t.urgency}</span><span class="muted">${esc(t.date)}</span></div>`}
function timeline(p){let ci=Math.max(0,stages.indexOf(p.status));return `<div class="timeline">${stages.map((s,i)=>{let ts=p.tasks.filter(t=>t.stage===s),d=ts.filter(t=>t.done).length,sp=ts.length?Math.round(d/ts.length*100):(i<ci?100:0);return `<div class="stage ${i<ci?'done':''} ${i===ci?'current':''}"><div class="dot">${i<ci?'✓':i+1}</div><div><h3>${s}</h3><small>${i===ci?'Current project stage':i<ci?'Past stage':'Upcoming stage'} · ${d}/${ts.length} tasks complete</small><div class="stagebar"><i style="width:${sp}%"></i></div></div><div class="right">${i===ci?'CURRENT':i<ci?'PAST':'NEXT'}</div></div>`}).join('')}</div>`}
function detail(p){let o=p.tasks.filter(t=>!t.done),d=p.tasks.filter(t=>t.done),crew=people.filter(pe=>p.tasks.some(t=>t.person===pe.id));$('detail').style.display='block';$('detail').innerHTML=`<div class="detailhead"><div><span class="pill">${p.status}</span><h2>${esc(p.name)}</h2><p class="muted">${esc(p.type)} · ${p.date||'No target'} · ${pct(p)}% complete</p></div><div class="actions"><button class="btn ghost" data-newtask="${p.id}">+ Add task</button><button class="btn ghost" data-tab="timeline">Timeline</button><button class="btn ghost" data-close-detail>Close</button></div></div><p class="muted">${esc(p.desc||'No notes yet.')}</p><div class="tabs">${['tasks','timeline','people','history'].map(x=>`<button class="tab ${tab===x?'active':''}" data-tab="${x}">${x==='people'?'People involved':x==='history'?'Completion history':x[0].toUpperCase()+x.slice(1)}</button>`).join('')}</div><div id="body"></div>`;let h=tab==='timeline'?timeline(p):tab==='people'?(crew.length?crew.map(x=>`<div class="person"><h3>${esc(x.name)}</h3><div class="muted">${esc(x.role||'')}${x.department?' · '+esc(x.department):''}</div><div class="muted">${esc(x.email||'No email')}</div><span class="level">${esc(x.level||'Core')}</span></div>`).join(''):empty('No crew assigned.','Assign people to tasks.')):tab==='history'?(d.length?d.slice().sort((a,b)=>(b.completedAt||'').localeCompare(a.completedAt||'')).map(t=>`<div class="history"><b>${esc(t.name)}</b> — completed by ${esc(t.completedBy||'Workspace user')}${t.completedAt?' · '+new Date(t.completedAt).toLocaleString():''}</div>`).join(''):'<div class="muted">No completed tasks yet.</div>'):`<div class="sectionhead"><h2>Open tasks</h2><span class="muted">${o.length} remaining</span></div>${o.map(t=>taskRow(t,p)).join('')||'<div class="muted">All tasks complete.</div>'}<div class="sectionhead" style="margin-top:25px"><h2>Completed</h2></div>${d.map(t=>taskRow(t,p)).join('')}`;$('body').innerHTML=h}
function render(){let all=projects.flatMap(p=>p.tasks.map(t=>({...t,p}))),open=all.filter(x=>!x.done),done=all.filter(x=>x.done);$('stats').innerHTML=`<div class="stat"><b>${projects.length}</b><span>Projects</span></div><div class="stat"><b>${open.length}</b><span>Open tasks</span></div><div class="stat"><b>${open.filter(x=>x.urgency==='high').length}</b><span>Urgent</span></div><div class="stat"><b>${done.length}</b><span>Completed</span></div>`;let c=projects.map(card).join('');$('dash').innerHTML=c||empty('Start your slate.','Create your first project.');$('projectGrid').innerHTML=c||empty('No projects yet.','Your slate is blank.');$('taskList').innerHTML=open.concat(done).map(x=>taskRow(x,x.p)).join('')||empty('Nothing on the board.','Create a project first.');$('scheduleList').innerHTML=open.filter(x=>x.date).sort((a,b)=>a.date.localeCompare(b.date)).map(x=>taskRow(x,x.p)).join('')||empty('No dated tasks.','Add due dates to see them here.');$('peopleList').innerHTML=people.length?people.map(x=>`<div class="person"><h3>${esc(x.name)}</h3><div class="muted">${esc(x.role||'')}${x.department?' · '+esc(x.department):''}</div><div class="muted">${esc(x.email||'No email')}</div><span class="level">${esc(x.level||'Core')}</span></div>`).join(''):empty('Your crew starts here.','Add collaborators and contacts.');if(selected){let p=projects.find(x=>x.id===selected);if(p)detail(p)}}
function go(v){document.querySelectorAll('.view').forEach(x=>x.classList.remove('active'));$(v).classList.add('active');document.querySelectorAll('.nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===v));$('crumb').textContent='Workspace / '+v[0].toUpperCase()+v.slice(1);if(v!=='projects')selected=null;render()}
const openM=id=>$(id).classList.add('open'),closeM=()=>document.querySelectorAll('.modal').forEach(x=>x.classList.remove('open'));
function openTask(pid){if(!projects.length)return openM('projectModal');$('taskProject').innerHTML=projects.map(p=>`<option value="${p.id}">${esc(p.name)}</option>`).join('');$('taskPerson').innerHTML='<option value="">Unassigned</option>'+people.map(p=>`<option value="${p.id}">${esc(p.name)}</option>`).join('');$('taskStage').innerHTML=stages.map(s=>`<option>${s}</option>`).join('');if(pid){$('taskProject').value=pid;$('taskStage').value=projects.find(p=>p.id===pid)?.status||'Development'}openM('taskModal')}
function initials(name){return String(name||'FH').trim().split(/\s+/).slice(0,2).map(x=>x[0]||'').join('').toUpperCase()||'FH'}
function avatarMarkup(){let u=profile?.avatar_url||user?.user_metadata?.avatar_url||user?.user_metadata?.picture||'';let name=profile?.display_name||user?.user_metadata?.full_name||user?.email||'Profile';return u?`<img class="miniavatar" src="${esc(u)}" alt=""><span class="accountname">${esc(name)}</span>`:`<span class="miniavatar fallback">${esc(initials(name))}</span><span class="accountname">${esc(name)}</span>`}
function authUI(){let b=$('signin');if(!user){b.classList.remove('signed');b.textContent='Sign in with Google';$('accountMenu').classList.remove('open');return}b.classList.add('signed');b.innerHTML=avatarMarkup()}
function fillProfileForm(firstTime=false){profileFirstTime=firstTime;let m=$('profileModal'),f=$('profileForm'),meta=user?.user_metadata||{},name=profile?.display_name||meta.full_name||meta.name||'',avatar=profile?.avatar_url||meta.avatar_url||meta.picture||'';m.classList.toggle('firsttime',firstTime);$('profileEyebrow').textContent=firstTime?'Welcome to Framehouse':'Your Framehouse profile';$('profileTitle').textContent=firstTime?'Set up your profile':'Edit profile';$('profileCopy').textContent=firstTime?'A few details now make your workspace feel like yours.':'Update how you appear inside your production workspace.';f.elements.display_name.value=name;f.elements.email.value=user?.email||'';f.elements.job_title.value=profile?.job_title||'';f.elements.company.value=profile?.company||'';f.elements.phone.value=profile?.phone||'';f.elements.city.value=profile?.city||'';f.elements.bio.value=profile?.bio||'';$('avatarPreview').innerHTML=avatar?`<img src="${esc(avatar)}" alt="">`:`<span>${esc(initials(name))}</span>`;openM('profileModal')}
async function loadProfile(){if(!sb||!user)return;let {data,error}=await sb.from('profiles').select('*').eq('user_id',user.id).maybeSingle();if(error){console.error('Profile load failed',error);return}profile=data||null;authUI();if(!profile)fillProfileForm(true)}
async function handleSession(session){user=session?.user||null;profile=null;authUI();if(user)await loadProfile()}
document.addEventListener('click',e=>{let v=e.target.closest('[data-view]');if(v)return go(v.dataset.view);let n=e.target.closest('[data-new]');if(n)return n.dataset.new==='project'?openM('projectModal'):n.dataset.new==='task'?openTask():openM('personModal');let o=e.target.closest('[data-open]');if(o){selected=o.dataset.open;tab='tasks';go('projects');selected=o.dataset.open;return detail(projects.find(x=>x.id===selected))}let nt=e.target.closest('[data-newtask]');if(nt)return openTask(nt.dataset.newtask);let tb=e.target.closest('[data-tab]');if(tb&&selected){tab=tb.dataset.tab;return detail(projects.find(x=>x.id===selected))}if(e.target.closest('[data-close]'))return closeM();if(e.target.closest('[data-close-detail]')){$('detail').style.display='none';selected=null}if(!e.target.closest('.accountwrap'))$('accountMenu').classList.remove('open')});
document.addEventListener('change',e=>{let x=e.target.closest('[data-toggle]');if(!x)return;let [pid,tid]=x.dataset.toggle.split('|'),p=projects.find(a=>a.id===pid),t=p?.tasks.find(a=>a.id===tid);if(!t)return;t.done=x.checked;t.completedBy=t.done?(people.find(a=>a.id===t.person)?.name||profile?.display_name||user?.user_metadata?.full_name||user?.email||'Workspace user'):'';t.completedAt=t.done?new Date().toISOString():'';save()});
$('projectForm').onsubmit=e=>{e.preventDefault();let f=new FormData(e.target),type=f.get('type'),defs=raw[type]||raw.Other;projects.unshift({id:uid(),name:f.get('name').trim(),type,status:f.get('status'),date:f.get('date'),desc:f.get('desc').trim(),tasks:defs.map((d,i)=>normT({name:d[1],stage:d[0],urgency:i<2?'high':i<5?'medium':'low'}))});e.target.reset();closeM();save();go('projects')};
$('taskForm').onsubmit=e=>{e.preventDefault();let f=new FormData(e.target),p=projects.find(x=>x.id===f.get('project'));if(!p)return;p.tasks.push(normT({name:f.get('name').trim(),stage:f.get('stage'),date:f.get('date'),urgency:f.get('urgency'),person:f.get('person')}));e.target.reset();closeM();save();go('tasks')};
$('personForm').onsubmit=e=>{e.preventDefault();let f=new FormData(e.target);people.push({id:uid(),name:f.get('name').trim(),role:f.get('role').trim(),department:f.get('department').trim(),phone:f.get('phone').trim(),email:f.get('email').trim(),level:f.get('level')});e.target.reset();closeM();save();go('people')};
$('signin').onclick=async()=>{if(!sb)return alert('Authentication could not start. Please refresh and try again.');if(user){$('accountMenu').classList.toggle('open');return}let {error}=await sb.auth.signInWithOAuth({provider:'google',options:{redirectTo:`${location.origin}/app.html`,scopes:'openid email profile'}});if(error)alert('Google sign-in failed: '+error.message)};
$('editProfileBtn').onclick=()=>{if(user){$('accountMenu').classList.remove('open');fillProfileForm(false)}};
$('signOutBtn').onclick=async()=>{if(!sb)return;await sb.auth.signOut();$('accountMenu').classList.remove('open');await handleSession(null)};
$('profileCancelBtn').onclick=()=>{if(!profileFirstTime)$('profileModal').classList.remove('open')};
$('profileForm').onsubmit=async e=>{e.preventDefault();if(!user||!sb)return;let f=new FormData(e.target),btn=$('profileSaveBtn');btn.disabled=true;btn.textContent='Saving…';let payload={user_id:user.id,display_name:String(f.get('display_name')||'').trim(),job_title:String(f.get('job_title')||'').trim(),company:String(f.get('company')||'').trim(),phone:String(f.get('phone')||'').trim(),city:String(f.get('city')||'').trim(),bio:String(f.get('bio')||'').trim(),avatar_url:profile?.avatar_url||user.user_metadata?.avatar_url||user.user_metadata?.picture||null};let {data,error}=await sb.from('profiles').upsert(payload,{onConflict:'user_id'}).select().single();btn.disabled=false;btn.textContent='Save profile';if(error){alert('Could not save profile: '+error.message);return}profile=data;profileFirstTime=false;$('profileModal').classList.remove('open');authUI()};
async function initAuth(){if(!sb){authUI();return}let {data,error}=await sb.auth.getSession();if(error)console.error('Auth session error',error);await handleSession(data?.session||null);sb.auth.onAuthStateChange(async(_event,session)=>{await handleSession(session)})}
render();initAuth();